### PR TITLE
Code cleanup as proposed during 2018-01-23 meeting

### PR DESCRIPTION
**Pull request by andrewcarreiro**
https://hackmd.io/s/SJZsjLSHG

### CODE REVIEW

**Comment by andrewcarreiro** [comment]
Also, I removed the dependency on Ruby for development. Since we're building a front end js app, we might as well use npm to serve the development version.

**Comment by andrewcarreiro** [comment]
@patcon can you review and merge? This will help https://github.com/CivicTechTO/toronto-shelter-map/issues/8

**Comment by patcon** [comment]
Reviewing now! Sorry for delay. Can resolve merge conflicts myself, I think

**Review by patcon — APPROVED** [review]

**Comment by patcon** [comment]
:tada: Done and done! Sorry for delay on this Andrew...! Always feel free to re-ping -- I will never take offense, and try to be more responsive :)

**Comment by andrewcarreiro** [comment]
Thanks @patcon!

**Pull request merged**
